### ISSUE TITLE
MediaPlayer not working

### ISSUE THREAD

**Issue by ishigo1987** [fax1ty/tabris-plugin-mediaplayer#1]
Hello, i tried
![Screenshot_20200529-090852](https://user-images.githubusercontent.com/12398336/83237349-ca50ae80-a18c-11ea-8fbb-358e72e29a49.jpg)
 the plugin and i can't succeed to play an audio
First Try
```JAVASCRIPT
const{MediaPlayer} = require("tabris");
let mediaPlayer = new MediaPlayer({ url: 'https://www.s3-us-west-2.amazonaws.com/series-stream/Fruitful+Repentance/CD+1+-++Fruitful+Repentance.mp3' });
mediaPlayer.start();
```
I've this error

**Comment by ishigo1987** [comment]
Second try
```JAVASCRIPT
let mediaPlayer = new MediaPlayer({ url: 'https://www.s3-us-west-2.amazonaws.com/series-stream/Fruitful+Repentance/CD+1+-++Fruitful+Repentance.mp3' });
mediaPlayer.start();
```
i've this error
![Screenshot_20200529-090814](https://user-images.githubusercontent.com/12398336/83237502-e9e7d700-a18c-11ea-8df7-23b5f4688250.jpg)

**Comment by fax1ty** [comment]
@ishigo1987 https://github.com/fax1ty/tabris-plugin-mediaplayer/blob/053f81ca19118dd6ece7abc8687664c5959444b3/plugin.xml#L2
I didn't notice. I copied the repository from another my plugin as "boilerplate" and didn't change the name of the plugin in one place, so the JS part doesn't go there
![image](https://user-images.githubusercontent.com/26363214/83254574-0f420880-a1c0-11ea-84c3-c5193830dd41.png)
Quick fix

**Comment by fax1ty** [comment]
Should be covered by https://github.com/fax1ty/tabris-plugin-mediaplayer/commit/0de93d677ed1b78c2c3ab196cbae613be36f72b4

**Comment by ishigo1987** [comment]
![Screenshot_20200529-194735](https://user-images.githubusercontent.com/12398336/83294792-d026ae00-a1e5-11ea-9811-676dba8f99f7.jpg)
@fax1ty  I've the same bug, it's look like you forgot something with the url

**Comment by fax1ty** [comment]
@ishigo1987 https://github.com/fax1ty/tabris-plugin-mediaplayer/commit/4c2191b7a8e26bfa132f105b6b526431188fa7bf I didn't think it was necessary

**Comment by ishigo1987** [comment]
@fax1ty the error did not change, I have the impress that we miss something, on the error we say that the problem with the url comes from line 16, and also why mediaPlayer.start() does not give while for the url apparently the error is just a warning?

**Comment by fax1ty** [comment]
@ishigo1987 Maybe something like this https://github.com/fax1ty/tabris-plugin-mediaplayer/commit/880a25796594d0a4494058af1020d477da553f8a

**Comment by ishigo1987** [comment]
Ok i test and i will let you know

**Comment by ishigo1987** [comment]
@fax1ty  same error, it looks like you've no reference inside your mediaplayer.js to url or autoplay... Ect, are you sure that everything is ok on the native side?
![Screenshot_20200601-134303](https://user-images.githubusercontent.com/12398336/83410521-6fc68500-a40e-11ea-9acf-a53797819b01.jpg)

**Comment by fax1ty** [comment]
@ishigo1987 https://github.com/fax1ty/tabris-plugin-mediaplayer/commit/d3e6454f7dcd6e2c5190d141aea975e1a9998afc

**Comment by ishigo1987** [comment]
@fax1ty 
 ```JAVASCRIPT
tabris.NativeObject.defineProperties(BarcodeScannerView.prototype
```
I think that you need to remove BarcodeScanner

**Comment by fax1ty** [comment]
@ishigo1987 https://github.com/fax1ty/tabris-plugin-mediaplayer/commit/6f8bf144f52d802b74af2f8c2b69f0d1221f6982

**Comment by ishigo1987** [comment]
Ok i test it right now

**Comment by ishigo1987** [comment]
@faxty you forgot to put the default attribute to URL I corrected it in the fork I made, I compiled and it remains the last error on the image below, I think the problem comes from the fact that the start() method is absent from the Javascript side, please look at the native side if you sent it to JS , and add it to JS
``` JAVASCRIPT
'url': {
    type: 'string',
    'default':false
  }
```

**Comment by ishigo1987** [comment]
@fax1ty No bug in the console but no sound is playing

**Comment by fax1ty** [comment]
@ishigo1987 Does the `ready` event work?
